# HPSC Notification API

obj-$(CONFIG_HPSC_MSG) += hpsc-msg.o hpsc-notif.o hpsc-monitor.o
obj-$(CONFIG_HPSC_MSG_TP_MBOX) += hpsc-msg-tp-mbox.o
obj-$(CONFIG_HPSC_MSG_TP_SHMEM) += hpsc-msg-tp-shmem.o

obj-$(CONFIG_HPSC_MBOX_USERSPACE) += hpsc-mbox-userspace.o
obj-$(CONFIG_HPSC_SHMEM) += hpsc-shmem.o
