# HPSC Notification API

obj-y =
obj-n += hpsc-notif.o
obj-$(CONFIG_HPSC_MBOX_USERSPACE) += hpsc-mbox-userspace.o
obj-$(CONFIG_HPSC_MBOX_KERNEL) += hpsc-mbox-kernel.o
obj-$(CONFIG_HPSC_SHMEM) += hpsc-shmem.o
obj-$(CONFIG_HPSC_KSHMEM) += hpsc-kshmem.o
obj-n += hpsc-msg.o
obj-n += hpsc-monitor.o
